name: Java CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven${{ hashFiles('**pom.xml') }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Program
        run: java -cp target/gha_hello_world-1.0-SNAPSHOT.jar org.example.Main > output.txt
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: output-log
          path: output.txt